receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  # Replace 'logging' with 'debug'
  debug:
    verbosity: detailed  # Can be 'normal' or 'detailed'
  
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  otlp/jaeger:
    endpoint: "jaeger:4317"  # Using OTLP receiver port
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]