# Generated by Django 5.2 on 2025-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='core_transa_user_id_c94326_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-timestamp'], name='core_transa_timesta_a40780_idx'),
        ),
    ]
